-- Auto-generated menu seed for LunchHub
-- Run AFTER schema.sql

insert into public.restaurants (id, name) values ('malkata-vereya', 'Малката Вереа')
  on conflict (id) do update set name = excluded.name;

-- Clear existing menu for a clean reseed
delete from public.menu_items where restaurant_id = 'malkata-vereya';

insert into public.menu_items (restaurant_id, day_index, name, price, category) values
  ('malkata-vereya', 1, 'Пилешка супа', 2.1, 'soup'),
  ('malkata-vereya', 1, 'Топчета', 2.1, 'main'),
  ('malkata-vereya', 1, 'Шкембе чорба', 2.6, 'soup'),
  ('malkata-vereya', 1, 'Боб чорба', 2.0, 'soup'),
  ('malkata-vereya', 1, 'Таратор', 1.6, 'soup'),
  ('malkata-vereya', 1, 'Свинско винен кебап', 3.3, 'main'),
  ('malkata-vereya', 1, 'Свинско по ловджийски', 3.3, 'main'),
  ('malkata-vereya', 1, 'Пиле с ориз', 3.0, 'main'),
  ('malkata-vereya', 1, 'Пиле прясно зеле', 3.0, 'main'),
  ('malkata-vereya', 1, 'Кюфтета с доматен сос', 3.1, 'main'),
  ('malkata-vereya', 1, 'Чушка бюрек', 3.0, 'main'),
  ('malkata-vereya', 1, 'Мусака от тиквички', 2.9, 'main'),
  ('malkata-vereya', 1, 'Мусака', 3.1, 'main'),
  ('malkata-vereya', 1, 'Кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 1, 'Кебапче - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 1, 'Свинско шишче - 100 гр.', 1.4, 'main'),
  ('malkata-vereya', 1, 'Пилешка пържола с гарн.', 4.0, 'main'),
  ('malkata-vereya', 1, 'Свински бекон с гарн.', 4.2, 'main'),
  ('malkata-vereya', 1, 'Кашкавал пане с гарн.', 3.5, 'main'),
  ('malkata-vereya', 1, 'Шницел пане с гарн.', 3.4, 'main'),
  ('malkata-vereya', 1, 'Пържено кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 1, 'Омлет с гарнитура', 2.9, 'main'),
  ('malkata-vereya', 1, 'Пържени картофи - 200 гр.', 1.7, 'main'),
  ('malkata-vereya', 1, 'Пърж. картофи с сирене', 1.9, 'main'),
  ('malkata-vereya', 1, 'Крем карамел', 1.5, 'dessert'),
  ('malkata-vereya', 1, 'Мляко с ориз', 1.5, 'main'),
  ('malkata-vereya', 1, 'Кадаиф', 1.5, 'main'),
  ('malkata-vereya', 1, 'Крем Сердика', 1.5, 'dessert'),
  ('malkata-vereya', 2, 'Агнешка супа', 2.6, 'soup'),
  ('malkata-vereya', 2, 'Пилешка супа', 2.1, 'soup'),
  ('malkata-vereya', 2, 'Топчета', 2.1, 'main'),
  ('malkata-vereya', 2, 'Градинска/спанак', 1.7, 'main'),
  ('malkata-vereya', 2, 'Таратор', 1.6, 'soup'),
  ('malkata-vereya', 2, 'Шкембе', 2.6, 'main'),
  ('malkata-vereya', 2, 'Пача', 2.4, 'main'),
  ('malkata-vereya', 2, 'Свинско с грах', 3.3, 'main'),
  ('malkata-vereya', 2, 'Печено пил. бутче с гарн.', 3.2, 'main'),
  ('malkata-vereya', 2, 'Агнешка дроб сарма', 3.5, 'main'),
  ('malkata-vereya', 2, 'Пълн. чушки с кайма', 3.1, 'main'),
  ('malkata-vereya', 2, 'Кюфтета с бял сос', 3.0, 'main'),
  ('malkata-vereya', 2, 'Картофени кюфтета', 3.0, 'main'),
  ('malkata-vereya', 2, 'Гъби с ориз', 2.9, 'main'),
  ('malkata-vereya', 2, 'Пил. дроб с лук', 3.0, 'main'),
  ('malkata-vereya', 2, 'Кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 2, 'Кебапче - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 2, 'Свинско шишче - 100 гр.', 1.4, 'main'),
  ('malkata-vereya', 2, 'Свински бекон с гарн.', 4.2, 'main'),
  ('malkata-vereya', 2, 'Кашкавал пане с гарн.', 3.5, 'main'),
  ('malkata-vereya', 2, 'Шницел пане с гарн.', 3.4, 'main'),
  ('malkata-vereya', 2, 'Пържено кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 2, 'Пържени картофи - 200 гр.', 1.7, 'main'),
  ('malkata-vereya', 2, 'Пърж. картофи с сирене', 1.9, 'main'),
  ('malkata-vereya', 2, 'Крем карамел', 1.5, 'dessert'),
  ('malkata-vereya', 2, 'Мляко с ориз', 1.5, 'main'),
  ('malkata-vereya', 2, 'Макарони на фурна', 1.5, 'main'),
  ('malkata-vereya', 2, 'Крем Брюле', 1.5, 'dessert'),
  ('malkata-vereya', 3, 'Пилешка супа', 2.1, 'soup'),
  ('malkata-vereya', 3, 'Топчета', 2.1, 'main'),
  ('malkata-vereya', 3, 'Шкембе чорба', 2.6, 'soup'),
  ('malkata-vereya', 3, 'Гъбена', 2.0, 'main'),
  ('malkata-vereya', 3, 'Таратор', 1.6, 'soup'),
  ('malkata-vereya', 3, 'Свинско с ориз', 3.3, 'main'),
  ('malkata-vereya', 3, 'Пил. дроб сърма', 3.2, 'main'),
  ('malkata-vereya', 3, 'Имам баялдъ', 2.9, 'main'),
  ('malkata-vereya', 3, 'Скумрия в фолио с гарн.', 4.3, 'main'),
  ('malkata-vereya', 3, 'Гнездо с дом. сос', 3.1, 'main'),
  ('malkata-vereya', 3, 'Пържен хек с гарнитура', 3.9, 'main'),
  ('malkata-vereya', 3, 'Джолан с картофи', 3.9, 'main'),
  ('malkata-vereya', 3, 'Селски пай', 3.1, 'main'),
  ('malkata-vereya', 3, 'Кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 3, 'Кебапче - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 3, 'Свинско шишче - 100 гр.', 1.4, 'main'),
  ('malkata-vereya', 3, 'Пилешка пържола с гарн.', 4.0, 'main'),
  ('malkata-vereya', 3, 'Свински бекон с гарн.', 4.2, 'main'),
  ('malkata-vereya', 3, 'Кашкавал пане с гарн.', 3.5, 'main'),
  ('malkata-vereya', 3, 'Шницел пане с гарн.', 3.4, 'main'),
  ('malkata-vereya', 3, 'Пържено кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 3, 'Омлет с гарнитура', 2.9, 'main'),
  ('malkata-vereya', 3, 'Пържени картофи - 200 гр.', 1.7, 'main'),
  ('malkata-vereya', 3, 'Пърж. картофи с сирене', 1.9, 'main'),
  ('malkata-vereya', 3, 'Крем карамел', 1.5, 'dessert'),
  ('malkata-vereya', 3, 'Мляко с ориз', 1.5, 'main'),
  ('malkata-vereya', 3, 'Ашуре', 1.5, 'main'),
  ('malkata-vereya', 3, 'Крем Сердика', 1.5, 'dessert'),
  ('malkata-vereya', 4, 'Пилешка супа', 2.1, 'soup'),
  ('malkata-vereya', 4, 'Топчета', 2.1, 'main'),
  ('malkata-vereya', 4, 'Леща', 2.0, 'main'),
  ('malkata-vereya', 4, 'Пача', 2.4, 'main'),
  ('malkata-vereya', 4, 'Джолан', 2.4, 'main'),
  ('malkata-vereya', 4, 'Таратор', 1.6, 'soup'),
  ('malkata-vereya', 4, 'Пил. бутче със зеленчуци', 3.2, 'main'),
  ('malkata-vereya', 4, 'Свинско с фасул', 3.3, 'main'),
  ('malkata-vereya', 4, 'Боб с кренвирши', 3.2, 'main'),
  ('malkata-vereya', 4, 'Руло Стефани', 3.1, 'main'),
  ('malkata-vereya', 4, 'Пълнен патладжан с кайма', 3.1, 'main'),
  ('malkata-vereya', 4, 'Зеленчукова мусака', 2.9, 'main'),
  ('malkata-vereya', 4, 'Пан. патладжан с гарн.', 3.0, 'main'),
  ('malkata-vereya', 4, 'Свински дроб с гарн.', 3.2, 'main'),
  ('malkata-vereya', 4, 'Пил. крилца с гарнитура', 3.2, 'main'),
  ('malkata-vereya', 4, 'Кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 4, 'Кебапче - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 4, 'Свинско шишче', 1.4, 'main'),
  ('malkata-vereya', 4, 'Пилешка пържола с гарн.', 4.0, 'main'),
  ('malkata-vereya', 4, 'Свински бекон с гарн.', 4.2, 'main'),
  ('malkata-vereya', 4, 'Кашкавал пане с гарн.', 3.5, 'main'),
  ('malkata-vereya', 4, 'Шницел пане с гарн.', 3.4, 'main'),
  ('malkata-vereya', 4, 'Пържено кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 4, 'Омлет с гарнитура', 2.9, 'main'),
  ('malkata-vereya', 4, 'Пържени картофи - 200 гр.', 1.7, 'main'),
  ('malkata-vereya', 4, 'Пърж. картофи с сирене', 1.9, 'main'),
  ('malkata-vereya', 4, 'Яйца по панагюрски', 2.8, 'main'),
  ('malkata-vereya', 4, 'Крем карамел', 1.5, 'dessert'),
  ('malkata-vereya', 4, 'Мляко с ориз', 1.5, 'main'),
  ('malkata-vereya', 4, 'Бисквитена торта', 1.5, 'main'),
  ('malkata-vereya', 4, 'Крем Брюле', 1.5, 'dessert'),
  ('malkata-vereya', 5, 'Пилешка супа', 2.1, 'soup'),
  ('malkata-vereya', 5, 'Топчета', 2.1, 'main'),
  ('malkata-vereya', 5, 'Шкембе чорба', 2.6, 'soup'),
  ('malkata-vereya', 5, 'Боб чорба', 2.0, 'soup'),
  ('malkata-vereya', 5, 'Таратор', 1.6, 'soup'),
  ('malkata-vereya', 5, 'Свинско печено с гарн.', 3.9, 'main'),
  ('malkata-vereya', 5, 'Свинска кавърма', 3.8, 'main'),
  ('malkata-vereya', 5, 'Печ. бутче с картофи', 3.2, 'main'),
  ('malkata-vereya', 5, 'Гръцка мусака', 3.4, 'main'),
  ('malkata-vereya', 5, 'Пълнени тиквички', 3.0, 'main'),
  ('malkata-vereya', 5, 'Миш-маш', 2.9, 'main'),
  ('malkata-vereya', 5, 'Кюфте от тиквички - 100 гр.', 1.0, 'main'),
  ('malkata-vereya', 5, 'Кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 5, 'Кебапче - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 5, 'Свинско шишче - 100 гр.', 1.4, 'main'),
  ('malkata-vereya', 5, 'Свински бекон с гарн.', 4.2, 'main'),
  ('malkata-vereya', 5, 'Кашкавал пане с гарн.', 3.5, 'main'),
  ('malkata-vereya', 5, 'Шницел пане с гарн.', 3.4, 'main'),
  ('malkata-vereya', 5, 'Пържено кюфте - 100 гр.', 1.2, 'main'),
  ('malkata-vereya', 5, 'Омлет с гарнитура', 2.9, 'main'),
  ('malkata-vereya', 5, 'Пържени картофи - 200 гр.', 1.7, 'main'),
  ('malkata-vereya', 5, 'Пърж. картофи с сирене', 1.9, 'main'),
  ('malkata-vereya', 5, 'Крем карамел', 1.5, 'dessert'),
  ('malkata-vereya', 5, 'Мляко с ориз', 1.5, 'main'),
  ('malkata-vereya', 5, 'Крем Сердика', 1.5, 'dessert');
