-- Манджата: per-day menu from mandjata.com (ЛЯТО 2026), prices in EUR.
-- Removes Орешков, Царя, Pizza HOT, Тера. Run after migration_everyday.sql.

update public.orders set restaurant_id = null, restaurant_name = null
  where restaurant_id in ('oreshkov','tsarya','pizza-hot','tera');
delete from public.restaurants where id in ('oreshkov','tsarya','pizza-hot','tera');

insert into public.restaurants (id, name) values ('mandzhata','Манджата')
  on conflict (id) do update set name = excluded.name;
delete from public.menu_items where restaurant_id = 'mandzhata';
insert into public.menu_items (restaurant_id, day_index, name, price, category) values
  ('mandzhata', 1, 'Селска салата', 3.4, 'salad'),
  ('mandzhata', 1, 'Гръцка салата', 3.78, 'salad'),
  ('mandzhata', 1, 'Розов домат с трошено сирене и прясна чушка', 3.59, 'salad'),
  ('mandzhata', 1, 'Краставици с чери домати', 4.2, 'salad'),
  ('mandzhata', 1, 'Картофена салата с пресен лук', 2.8, 'salad'),
  ('mandzhata', 1, 'Леща чорба', 2.1, 'soup'),
  ('mandzhata', 1, 'Пилешка супа', 2.3, 'soup'),
  ('mandzhata', 1, 'Супа от свинско месо', 2.4, 'soup'),
  ('mandzhata', 1, 'Шкембе чорба', 2.4, 'soup'),
  ('mandzhata', 1, 'Таратор', 1.9, 'soup'),
  ('mandzhata', 1, 'Боб яхния', 2.65, 'soup'),
  ('mandzhata', 1, 'Ориз със спанак и яйце', 3.25, 'main'),
  ('mandzhata', 1, 'Картофи на фурна с масло и билки', 3.1, 'main'),
  ('mandzhata', 1, 'Лятна доматена манджа', 3.2, 'main'),
  ('mandzhata', 1, 'Пълнени чушки с ориз и сезонни зеленчуци', 3.5, 'main'),
  ('mandzhata', 1, 'Сирене по Шопски', 3.99, 'main'),
  ('mandzhata', 1, 'Яйца по Панагюрски', 3.3, 'main'),
  ('mandzhata', 1, 'Пиле Пилар', 4.35, 'main'),
  ('mandzhata', 1, 'Пилешко бутче с картофи на фурна', 3.6, 'main'),
  ('mandzhata', 1, 'Свински котлети с гъбен сос', 4.1, 'main'),
  ('mandzhata', 1, 'Свинско винен кебап с ориз', 3.6, 'main'),
  ('mandzhata', 1, 'Пилешка дроб сарма', 3.5, 'main'),
  ('mandzhata', 1, 'Пълнен патладжан Папуцаки', 4.4, 'main'),
  ('mandzhata', 1, 'Спагети Карбонара', 3.48, 'main'),
  ('mandzhata', 1, 'Кренвирши с кашкавал', 3.8, 'main'),
  ('mandzhata', 1, 'Рибни филенца с топено сирене', 4.2, 'main'),
  ('mandzhata', 1, 'Ципура на скара', 8.5, 'main'),
  ('mandzhata', 1, 'Шоколадов чийзкейк', 2.5, 'dessert'),
  ('mandzhata', 1, 'Торта Нутела с портокалови кори', 2.2, 'dessert'),
  ('mandzhata', 1, 'Бисквитена торта с маскарпоне и боровинки', 2.1, 'dessert'),
  ('mandzhata', 2, 'Мераклийска салата', 3.8, 'salad'),
  ('mandzhata', 2, 'Айсберг с пилешко', 4.3, 'salad'),
  ('mandzhata', 2, 'Домати с грилован патладжан и кубчета сирене', 3.6, 'salad'),
  ('mandzhata', 2, 'Корнишони с овче сирене и маслини Каламата', 4.15, 'salad'),
  ('mandzhata', 2, 'Зеленчуков борш', 2.1, 'soup'),
  ('mandzhata', 2, 'Супа топчета', 2.3, 'soup'),
  ('mandzhata', 2, 'Супа от селска кокошка', 2.4, 'soup'),
  ('mandzhata', 2, 'Боб чорба с бекон', 2.35, 'soup'),
  ('mandzhata', 2, 'Таратор', 1.9, 'soup'),
  ('mandzhata', 2, 'Леща яхния', 2.65, 'soup'),
  ('mandzhata', 2, 'Постен гювеч', 2.8, 'main'),
  ('mandzhata', 2, 'Ориз с тиквички и копър', 2.7, 'main'),
  ('mandzhata', 2, 'Пълнени тиквички с яйце и сирене', 3.4, 'main'),
  ('mandzhata', 2, 'Постно зеле с домати', 2.9, 'main'),
  ('mandzhata', 2, 'Пържен патладжан с доматен сос', 3.35, 'main'),
  ('mandzhata', 2, 'Талиатели с тиквички', 3.4, 'main'),
  ('mandzhata', 2, 'Лозови сарми с ориз, лук, морков и целина', 3.85, 'main'),
  ('mandzhata', 2, 'Пилешка пържола Капрезе', 5.35, 'main'),
  ('mandzhata', 2, 'Пилешко бутче с ориз', 3.6, 'main'),
  ('mandzhata', 2, 'Свинско дърпано', 3.9, 'main'),
  ('mandzhata', 2, 'Свинско по ловджийски', 3.55, 'main'),
  ('mandzhata', 2, 'Кюфтета по Чирпански', 3.8, 'main'),
  ('mandzhata', 2, 'Мусака', 3.55, 'main'),
  ('mandzhata', 2, 'Пилешки дробчета с лук', 3.1, 'main'),
  ('mandzhata', 2, 'Омлет с шунка и кашкавал', 3.8, 'main'),
  ('mandzhata', 2, 'Филе скумрия с доматен сос - плакия', 5.8, 'main'),
  ('mandzhata', 2, 'Хек пане', 3.8, 'main'),
  ('mandzhata', 2, 'Лаврак на скара', 8.5, 'main'),
  ('mandzhata', 2, 'Торта Бискоф', 2.4, 'dessert'),
  ('mandzhata', 2, 'Пухкави мъфини', 1.35, 'dessert'),
  ('mandzhata', 2, 'Лимонов Чийзкейк', 2.2, 'dessert'),
  ('mandzhata', 2, 'Торта Селска носталгия', 1.7, 'dessert'),
  ('mandzhata', 3, 'Овчарска салата', 4.2, 'salad'),
  ('mandzhata', 3, 'Салата Цезар', 4.6, 'salad'),
  ('mandzhata', 3, 'Розов домат с Бурата и рукола', 4.1, 'salad'),
  ('mandzhata', 3, 'Печена севрия с чеснова марината и пресен лук', 3.8, 'salad'),
  ('mandzhata', 3, 'Крем супа с целина и пащърнак', 2.1, 'soup'),
  ('mandzhata', 3, 'Супа пилешки дреболийки', 2.3, 'soup'),
  ('mandzhata', 3, 'Телешко варено', 3.8, 'soup'),
  ('mandzhata', 3, 'Шкембе чорба', 2.4, 'soup'),
  ('mandzhata', 3, 'Таратор', 1.9, 'soup'),
  ('mandzhata', 3, 'Боб яхния с целина и пащърнак', 2.7, 'soup'),
  ('mandzhata', 3, 'Ориз със зеленчуци и пармезан', 3.1, 'main'),
  ('mandzhata', 3, 'Киноа със зеленчуци', 3.2, 'main'),
  ('mandzhata', 3, 'Картофен пай със спанак и сирене', 3.1, 'main'),
  ('mandzhata', 3, 'Паниран карфиол със сос от сирена', 3.4, 'main'),
  ('mandzhata', 3, 'Талиатели с Босилеково песто', 3.75, 'main'),
  ('mandzhata', 3, 'Миш - маш', 3.3, 'main'),
  ('mandzhata', 3, 'Пиле четири сирена', 4.65, 'main'),
  ('mandzhata', 3, 'Картофена запеканка с бекон', 3.9, 'main'),
  ('mandzhata', 3, 'Свински каренца с Пепър сос', 6.2, 'main'),
  ('mandzhata', 3, 'Свински мръвки с гъби и пресен лук', 4.15, 'main'),
  ('mandzhata', 3, 'Кюфтета бял сос', 3.2, 'main'),
  ('mandzhata', 3, 'Лазаня Болонезе', 3.6, 'main'),
  ('mandzhata', 3, 'Пълнени тиквички с кайма и зеленчуци', 3.5, 'main'),
  ('mandzhata', 3, 'Пържен салам Камчия', 3.65, 'main'),
  ('mandzhata', 3, 'Пържен шаран', 5.2, 'main'),
  ('mandzhata', 3, 'Ципура на скара', 8.5, 'main'),
  ('mandzhata', 3, 'Торта Линд', 2.6, 'dessert'),
  ('mandzhata', 3, 'Крем Брюле', 1.7, 'dessert'),
  ('mandzhata', 3, 'Торта Бял шоколад и плодове', 2.45, 'dessert'),
  ('mandzhata', 3, 'Боровинков чийзкейк', 2.15, 'dessert'),
  ('mandzhata', 4, 'Капрезе', 4.1, 'salad'),
  ('mandzhata', 4, 'Гриловани тиквички с розов домат и млечен мус', 4.3, 'salad'),
  ('mandzhata', 4, 'Пастирска салата', 3.4, 'salad'),
  ('mandzhata', 4, 'Салата зеле с моркови', 2.45, 'salad'),
  ('mandzhata', 4, 'Зелена салата', 3.5, 'salad'),
  ('mandzhata', 4, 'Морковена крем супа', 2.1, 'soup'),
  ('mandzhata', 4, 'Пилешка супа', 2.3, 'soup'),
  ('mandzhata', 4, 'Супа топчета', 2.3, 'soup'),
  ('mandzhata', 4, 'Свинска джолан чорба', 2.4, 'soup'),
  ('mandzhata', 4, 'Таратор', 1.9, 'soup'),
  ('mandzhata', 4, 'Селска картофена яхния', 2.65, 'soup'),
  ('mandzhata', 4, 'Домати с ориз', 2.8, 'main'),
  ('mandzhata', 4, 'Пържени тиквички с чесново мляко', 3.2, 'main'),
  ('mandzhata', 4, 'Пържени чушки с доматен сос и сирене', 3.7, 'main'),
  ('mandzhata', 4, 'Броколи пане', 3.3, 'main'),
  ('mandzhata', 4, 'Кашкавал на фурна', 3.99, 'main'),
  ('mandzhata', 4, 'Бъркани яйца със сирене и зелен лук', 3.3, 'main'),
  ('mandzhata', 4, 'Медено пиле', 5.2, 'main'),
  ('mandzhata', 4, 'Пиле по градинарски', 3.85, 'main'),
  ('mandzhata', 4, 'Панирани свински филенца - Амон Ра', 4.6, 'main'),
  ('mandzhata', 4, 'Свинско яхния с картоф, целина и пащърнак', 3.7, 'main'),
  ('mandzhata', 4, 'Болярски сарми', 3.9, 'main'),
  ('mandzhata', 4, 'Пълнени чушки с кайма и ориз', 3.7, 'main'),
  ('mandzhata', 4, 'Боб с наденица', 3.2, 'main'),
  ('mandzhata', 4, 'Спагети Болонезе', 3.4, 'main'),
  ('mandzhata', 4, 'Сьомга филе със задушени зеленчуци', 8.6, 'main'),
  ('mandzhata', 4, 'Пъстърва пържена', 4.6, 'main'),
  ('mandzhata', 4, 'Чийзкейк Сан Себастиан', 2.2, 'dessert'),
  ('mandzhata', 4, 'Торта три шоколада', 2.65, 'dessert'),
  ('mandzhata', 4, 'Бишкотена торта Черноморец', 2.1, 'dessert'),
  ('mandzhata', 4, 'Торта Гараш', 2.45, 'dessert'),
  ('mandzhata', 5, 'Зелен микс с кедрови ядки', 4.2, 'salad'),
  ('mandzhata', 5, 'Патладжанена салата', 3.6, 'salad'),
  ('mandzhata', 5, 'Шопска салата', 3.4, 'salad'),
  ('mandzhata', 5, 'Снежанка', 3.0, 'salad'),
  ('mandzhata', 5, 'Табуле', 3.3, 'salad'),
  ('mandzhata', 5, 'Картофена крем супа', 2.1, 'soup'),
  ('mandzhata', 5, 'Супа пилешки дреболийки', 2.3, 'soup'),
  ('mandzhata', 5, 'Телешка застроена супа с ориз', 3.4, 'soup'),
  ('mandzhata', 5, 'Шкембе чорба', 2.4, 'soup'),
  ('mandzhata', 5, 'Таратор', 1.9, 'soup'),
  ('mandzhata', 5, 'Червена леща с целина и пащърнак', 3.15, 'soup'),
  ('mandzhata', 5, 'Ориз с гъби', 2.9, 'main'),
  ('mandzhata', 5, 'Славянски гювеч', 3.2, 'main'),
  ('mandzhata', 5, 'Пържени чушки с яйце и сирене', 3.65, 'main'),
  ('mandzhata', 5, 'Тортия с тиквички', 3.45, 'main'),
  ('mandzhata', 5, 'Пълнен патладжан със зеленчуци', 3.6, 'main'),
  ('mandzhata', 5, 'Броколи със сметана и синьо сирене', 3.25, 'main'),
  ('mandzhata', 5, 'Шницел от пилешко филе', 4.5, 'main'),
  ('mandzhata', 5, 'Пиле фрикасе', 3.6, 'main'),
  ('mandzhata', 5, 'Свинско джоланче с печени зеленчуци', 5.9, 'main'),
  ('mandzhata', 5, 'Свинско с ориз', 3.7, 'main'),
  ('mandzhata', 5, 'Гнездо от кайма с яйце', 4.55, 'main'),
  ('mandzhata', 5, 'Телешко задушено с гъби и бял ориз', 6.2, 'main'),
  ('mandzhata', 5, 'Лазаня с пушено пиле', 3.9, 'main'),
  ('mandzhata', 5, 'Лозови сарми с кайма и ориз', 3.8, 'main'),
  ('mandzhata', 5, 'Пържен шаран', 5.2, 'main'),
  ('mandzhata', 5, 'Хек пане', 3.8, 'main'),
  ('mandzhata', 5, 'Здравословен десерт с чиа и плодове', 2.5, 'dessert'),
  ('mandzhata', 5, 'Мляко с грис', 1.35, 'dessert'),
  ('mandzhata', 5, 'Морковена торта', 1.95, 'dessert'),
  ('mandzhata', 5, 'Торта шоколадова Сникърс', 2.5, 'dessert'),
  ('mandzhata', 0, 'Кюфте', 1.15, 'main'),
  ('mandzhata', 0, 'Кебапче', 1.15, 'main'),
  ('mandzhata', 0, 'Пилешко шишче', 1.7, 'main'),
  ('mandzhata', 0, 'Порция пилешки шишчета', 4.5, 'main'),
  ('mandzhata', 0, 'Свинско шишче', 1.8, 'main'),
  ('mandzhata', 0, 'Порция свински шишчета', 4.9, 'main'),
  ('mandzhata', 0, 'Карначета /порция/', 4.9, 'main'),
  ('mandzhata', 0, 'Татарско кюфте', 4.6, 'main'),
  ('mandzhata', 0, 'Дълго кюфте', 1.9, 'main'),
  ('mandzhata', 0, 'Порция дълги кюфтета', 4.7, 'main'),
  ('mandzhata', 0, 'Пилешка пържола от бут', 3.7, 'main'),
  ('mandzhata', 0, 'Свинска вратна пържола', 4.6, 'main'),
  ('mandzhata', 0, 'Свински каренца', 4.9, 'main'),
  ('mandzhata', 0, 'Бекончета на скара', 2.05, 'main'),
  ('mandzhata', 0, 'Пушен бекон на скара', 1.35, 'main'),
  ('mandzhata', 0, 'Свински уши на скара', 1.25, 'main'),
  ('mandzhata', 0, 'Свински дроб на скара', 0.95, 'main'),
  ('mandzhata', 0, 'Гриловани зеленчуци', 2.8, 'main'),
  ('mandzhata', 0, 'Филе скумрия на скара', 6.8, 'main'),
  ('mandzhata', 0, 'Франзелка с пшенично брашно', 0.6, 'main'),
  ('mandzhata', 0, 'Франзелка с царевично брашно', 0.6, 'main'),
  ('mandzhata', 0, 'Франзелка със слънчогледови семки', 0.6, 'main'),
  ('mandzhata', 0, 'Чесново хлебче', 1.1, 'main'),
  ('mandzhata', 0, 'Хлебче с риган и зехтин', 1.1, 'main'),
  ('mandzhata', 0, 'Пърленка с масло и мерудия', 1.1, 'main'),
  ('mandzhata', 0, 'Филия хляб', 0.13, 'main'),
  ('mandzhata', 0, 'Бюрек баничка с ориз, праз и маслини', 2.44, 'main'),
  ('mandzhata', 0, 'Кюфтета от леща', 1.02, 'main'),
  ('mandzhata', 0, 'Ориз с горски гъби', 0.91, 'main'),
  ('mandzhata', 0, 'Печен боб с кисело зеле', 0.76, 'main'),
  ('mandzhata', 0, 'Пълнени чушки с боб и зеленчуци', 0.91, 'main'),
  ('mandzhata', 0, 'Зелеви сарми с ориз, стафиди и зеленчуци', 0.91, 'main'),
  ('mandzhata', 0, 'Лозови сарми с лимонов дресинг', 0.86, 'main'),
  ('mandzhata', 0, 'Печени чушки с чесън', 0.89, 'main'),
  ('mandzhata', 0, 'Смилянски боб с чушки и лук', 0.84, 'main'),
  ('mandzhata', 0, 'Домашна туршия', 0.81, 'main'),
  ('mandzhata', 0, 'Картофена салата', 0.66, 'salad'),
  ('mandzhata', 0, 'Крем карамел', 1.5, 'dessert'),
  ('mandzhata', 0, 'Мляко с ориз', 1.5, 'dessert'),
  ('mandzhata', 0, 'Макарони на фурна', 1.5, 'dessert'),
  ('mandzhata', 0, 'Домашна бисквитена торта', 1.4, 'dessert'),
  ('mandzhata', 0, 'Грис халва със стафиди', 1.7, 'dessert'),
  ('mandzhata', 0, 'Цедено мляко с мед и орехи', 1.8, 'dessert'),
  ('mandzhata', 0, 'Свежа плодова салата', 2.25, 'dessert'),
  ('mandzhata', 0, 'Бисквитена торта с маскарпоне', 1.95, 'dessert'),
  ('mandzhata', 0, 'Баница с тиква и орехи /Тиквеник/', 1.93, 'dessert'),
  ('mandzhata', 0, 'Рачел', 0.91, 'dessert'),
  ('mandzhata', 0, 'Баклава', 1.93, 'dessert'),
  ('mandzhata', 0, 'Печена тиква с мед и орехи', 0.76, 'dessert'),
  ('mandzhata', 0, 'Минерална вода Банкя 0.500 л.', 0.66, 'main'),
  ('mandzhata', 0, 'Изворна вода Роса 0.500 л.', 0.66, 'main'),
  ('mandzhata', 0, 'Минерална вода Банкя 1.5 л.', 0.82, 'main'),
  ('mandzhata', 0, 'Изворна вода Роса 1.5 л.', 0.82, 'main'),
  ('mandzhata', 0, 'Швепс Сода 0.5 л.', 0.77, 'main'),
  ('mandzhata', 0, 'Швепс Сода 1.25 л.', 1.07, 'main'),
  ('mandzhata', 0, 'Швепс Тоник, Розов Тоник и Мандарина 1.25 л.', 1.79, 'main'),
  ('mandzhata', 0, 'Кока Кола, Фанта, Спрайт - ПВЦ 0.500 л.', 1.33, 'main'),
  ('mandzhata', 0, 'Кока Кола, Фанта, Спрайт - ПВЦ 1.5 л.', 1.84, 'main'),
  ('mandzhata', 0, 'Енергийна напитка XIXO КЕН 0.250 л.', 0.71, 'main'),
  ('mandzhata', 0, 'Енергийна напитка Монстър 0.5 л.', 1.22, 'main'),
  ('mandzhata', 0, 'Ариана кен 0.500 л.', 1.07, 'main'),
  ('mandzhata', 0, 'Загорка Специално кен 0.500 л.', 1.17, 'main'),
  ('mandzhata', 0, 'Хайникен кен 0.500 л.', 1.63, 'main'),
  ('mandzhata', 0, 'Ариана Радлер кен 0.330 л.', 0.92, 'main'),
  ('mandzhata', 0, 'Хайникен кен 0.330 л. 0% алкохол', 1.33, 'main'),
  ('mandzhata', 0, 'Ариана 1.2 л.', 1.43, 'main'),
  ('mandzhata', 0, 'Загорка 1 л.', 1.48, 'main');

notify pgrst, 'reload schema';
